### ISSUE TITLE
монте карло 1 урок

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/python-Tatiana#11]
[Monte_carlo.json](https://github.com/user-attachments/files/17457378/Monte_carlo.json)

**Comment by kypena** [comment]
подскажи, пожалуйста, как json в ipynb конветировать.

**Comment by ruslansenatorov** [comment]
> подскажи, пожалуйста, как json в ipynb конветировать.

конвертировать? может ты имела ввиду переименовать?

**Comment by Umekko** [comment]
Accepted

**Comment by ruslansenatorov** [comment]
[monte_carlo.json](https://github.com/user-attachments/files/17503763/monte_carlo.json) 2 lesson

**Comment by ruslansenatorov** [comment]
[2_probability_and_statistics_generators_and_monte_carlo.json](https://github.com/user-attachments/files/17584850/2_probability_and_statistics_generators_and_monte_carlo.json)
