### ISSUE TITLE
python/python/Monte_carlo.ipynb:1:0: C0103: Module name "Monte_carlo" doesn't conform to snake_case naming style (invalid-name)

### ISSUE THREAD

**Issue by Zakieva** [SENATOROVAI/python-Tatiana#21]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Hash commit / link

d67067d3ec7bedfdb6ee9752e2a71bcf026268b0

### Attach a full screenshot and write what did you do to fix the problem?

![изображение](https://github.com/user-attachments/assets/3b9b2061-a0e0-4a1c-a316-d6f71d326324)

### Error from the terminal / Code

3s
Run pylint --max-line-length=79 --const-naming-style=any --disable=E2515,C0303,E1101,R1716,E0401,W1514,C0200,C0114,C0301,E0602,W0104,C0302,R0801,E1136 --disable=import-error $(git ls-files '*.py' '*.ipynb')
************* Module "python/Made-Easy/\321\201hapter_13_modules_and_packages.ipynb"
"python/Made-Easy/\321\201hapter_13_modules_and_packages.ipynb":1:0: F0001: No module named "python/Made-Easy/\321\201hapter_13_modules_and_packages.ipynb" (fatal)
************* Module "python/Made-Easy/\321\201hapter_5_\321\201ontrol_flow_statements.ipynb"
"python/Made-Easy/\321\201hapter_5_\321\201ontrol_flow_statements.ipynb":1:0: F0001: No module named "python/Made-Easy/\321\201hapter_5_\321\201ontrol_flow_statements.ipynb" (fatal)
************* Module Sets
math/set_theory/Sets.ipynb:1:0: C0103: Module name "Sets" doesn't conform to snake_case naming style (invalid-name)
************* Module python.OOP.OOP_conspect_mine
python/OOP/OOP_conspect_mine.ipynb:1:0: C0103: Module name "OOP_conspect_mine" doesn't conform to snake_case naming style (invalid-name)
************* Module python.OOP.oop_3_callable-objects_instances
python/OOP/oop_3_callable-objects_instances.ipynb:1:0: C0103: Module name "oop_3_callable-objects_instances" doesn't conform to snake_case naming style (invalid-name)
************* Module python.python.Monte_carlo
python/python/Monte_carlo.ipynb:1:0: C0103: Module name "Monte_carlo" doesn't conform to snake_case naming style (invalid-name)
************* Module python.python.lesson_01-03
python/python/lesson_01-03.ipynb:1:0: C0103: Module name "lesson_01-03" doesn't conform to snake_case naming style (invalid-name)

-----------------------------------
Your code has been rated at 0.00/10

### Expected behavior

Пройти все линтеры.

### Actual behavior

C0103. Run linters.

**Comment by ruslansenatorov** [comment]
[chapter_1_to_.py.zip](https://github.com/user-attachments/files/17625152/chapter_1_to_.py.zip)

**Comment by kypena** [comment]
done
