### ISSUE TITLE
ЗАКРАТЬ ОШИБКИ

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/python-Tatiana#23]
### Feature description

flake8
<img width="1267" alt="Screenshot 2024-10-31 at 12 31 01 PM" src="https://github.com/user-attachments/assets/c1eb436f-6107-4c17-a151-67c152da0f65">

**Comment by ruslansenatorov** [comment]
MYPY 36 errors

![image](https://github.com/user-attachments/assets/26431172-5cf6-4145-a1e5-ac5e8168a86a)

**Comment by ruslansenatorov** [comment]
pylint
![image](https://github.com/user-attachments/assets/86673c4f-79d5-4827-b0e4-28cd7e0049b3)
![image](https://github.com/user-attachments/assets/48fef688-e813-4a66-b975-4e5ebc4d2a5a)
![image](https://github.com/user-attachments/assets/2884c228-ac72-433a-af7c-05bd1cb0144e)
![image](https://github.com/user-attachments/assets/3e9b3a5c-792b-4a0b-822e-2a815eb461cb)
![image](https://github.com/user-attachments/assets/5ea94309-0eb8-4571-b478-87087080e76b)

**Comment by ruslansenatorov** [comment]
docs 

![image](https://github.com/user-attachments/assets/47b5e899-ccbe-4acd-a0d2-b437b1ce8241)

**Comment by kypena** [comment]
done
