### ISSUE TITLE
E0001: unterminated f-string literal (detected at line 69) (<unknown>, line 69) (syntax-error)

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/python-Tatiana#24]
https://github.com/SENATOROVAI/python-Tatiana/blob/cc3dd506693f1f5966f0386d4c650451e2332a8b/python/Made-Easy/chapter_5_control_flow_statements.py#L69-L70

**Comment by kypena** [comment]
accepted

**Comment by kypena** [comment]
Исправлено
