### ISSUE TITLE
 C0301: Line too long (81/79) (line-too-long)

### ISSUE THREAD

**Issue by kypena** [SENATOROVAI/python-Tatiana#31]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a full screenshot and write what did you do to fix the problem?

**Помогите исправить ошибку согласно титулу. Какие меры были приняты:**
1) Пробовала часть кода убирать в переменную, но в ланном случае не сработало.
2) Также пробовала деалть построчный перенос, те перед точкой ставить \ и переносить.
3) Убирала пробелы возле запятых. Пайтон их возвращает обратно. 
**Код к отором есть такой тип ошибки :**
 a)  pd.Series([dice.sample(n_, replace=True).mean() for n_ in range(1, 1000)]).plot()
b) data_0: list[float] = [dice.sample(100, replace=True).mean() for _ in range(1000)]
c) data_4: list[float] = [dice.sample(1000, replace=True).mean() for _ in range(10000)]
d) data_5: list[float] = [lognorm.rvs(s_param_2, size=10000).mean() for _ in range(10000)]

### Error from the terminal / Code

pd.Series([dice.sample(n_, replace=True).mean() for n_ in range(1, 1000)]).plot()
data_0: list[float] = [dice.sample(100, replace=True).mean() for _ in range(1000)]
data_4: list[float] = [dice.sample(1000, replace=True).mean() for _ in range(10000)]
data_5: list[float] = [lognorm.rvs(s_param_2, size=10000).mean() for _ in range(10000)]

### Expected behavior

отсутствие ошибки 

### Actual behavior

ошибка линтера nbqa-pylint

**Comment by ruslansenatorov** [comment]
в переменную присвой 

dice.sample(100, replace=True).mean()
